# SPDX-FileCopyrightText: 2025-2026 Mateusz Krawczuk <mateusz.krawczuk@cybrixsystems.com>
# SPDX-License-Identifier: GPL-2.0-or-later

# These are supported funding model platforms

github: [MateuszKrawczuk]

