# SPDX-FileCopyrightText: 2017-2020 Sergio Carlavilla <carlavilla @ mailbox.org>
# SPDX-License-Identifier: GPL-2.0-or-later

# These are supported funding model platforms

github: [MateuszKrawczuk]

